import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"


const fontPoppins = Poppins({
  weight: ["400", "700"],
  subsets: ['latin']

})

export const metadata: Metadata = {
  title: "Happy Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontPoppins.className}>{children}</body>
    </html>
  );
}
